version: '3.8'

services:
  my-fastapi-service:
    image: solarslurpie/obsidian-transcriber-service:latest
    container_name: obsidian-transcriber-service
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
